### ISSUE TITLE
Dark version

### ISSUE THREAD

**Issue by toasty-sunbeam** [duien/princess-syntax#1]
I like what you've got going on here. Could we get a dark version?

**Comment by duien** [comment]
I don't currently have any plans to make a dark version, but if you'd like to borrow the color palette to make one, I'd love to see what you come up with!

If you're looking for a dark theme with a somewhat similar color palette, I'd recommend taking a look at [Whimsy](https://atom.io/packages/whimsy-syntax) or [Dracula](https://atom.io/packages/dracula-theme)

**Comment by toasty-sunbeam** [comment]
That's totally fair. Thanks for the recommendations--I think Dracula is pretty close to what I'm looking for.
